# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "memcache-client"
gem "foreman"
gem "puma"
gem "mysql2"
gem "rack-flash3"
gem 'rack-lineprof', git: 'https://github.com/kainosnoema/rack-lineprof'
gem 'pry-byebug'
gem 'pry-doc'
